name: Cargo Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: ModuRL_Gym - latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
